"""Read allpapers.bib into the four fields that tie a paper to its citation key: key, DOI, title and year.

A small parser is enough here. The file is generated by the thesis repository's combine-references.py from Paperpile exports and the fetch script, and only a handful of fields are needed, so a full BibTeX library would add a dependency for nothing.
"""

import re
import unicodedata

from pylatexenc.latex2text import LatexNodes2Text

from literature_rag.records import BibEntry

ENTRY_START = re.compile(r"@\s*(\w+)\s*\{\s*([^,\s]+)\s*,")
FIELD_NAME = re.compile(r"[\s,]*([A-Za-z][\w-]*)\s*=\s*")
DOI = re.compile(r"10\.\d{4,9}/[^\s\"<>{}]+")
NOT_ALPHANUMERIC = re.compile(r"[^a-z0-9]+")
BIBITEM = re.compile(r"\\bibitem(?:\[[^\]]*\])?\{([^}]+)\}")
# Entries of these types hold no reference; @string is an abbreviation, @comment and @preamble are not entries.
NOT_ENTRIES = {"comment", "preamble", "string"}

LATEX = LatexNodes2Text()


def read_value(body: str, start: int) -> tuple[str, int]:
    """Read one field value that begins at body[start]: {braced}, "quoted" or bare. Return it and the position after it."""
    if body[start] == "{":
        depth = 0
        for end in range(start, len(body)):
            depth += {"{": 1, "}": -1}.get(body[end], 0)
            if depth == 0:
                return body[start + 1 : end], end + 1
        return body[start + 1 :], len(body)
    if body[start] == '"':
        depth = 0
        for end in range(start + 1, len(body)):
            char = body[end]
            depth += {"{": 1, "}": -1}.get(char, 0)
            if char == '"' and depth == 0 and body[end - 1] != "\\":
                return body[start + 1 : end], end + 1
        return body[start + 1 :], len(body)
    match = re.match(r"[^,}\s]*", body[start:])
    return match.group(0), start + match.end()


def parse_fields(body: str) -> dict[str, str]:
    """The fields of one entry, from the text after its key. Names are lowercased, and the first occurrence of a field wins."""
    fields: dict[str, str] = {}
    position = 0
    while match := FIELD_NAME.match(body, position):
        value_start = match.end()
        if value_start >= len(body):
            break
        value, position = read_value(body, value_start)
        fields.setdefault(match.group(1).lower(), " ".join(value.split()))
    return fields


def split_entries(text: str) -> list[tuple[str, str, str]]:
    """Every entry in a .bib file as (type, key, body), where body is the text between the key and the closing brace."""
    entries = []
    position = 0
    while match := ENTRY_START.search(text, position):
        entry_type, key = match.group(1).lower(), match.group(2)
        # The entry ends where the brace opened after the type closes again.
        depth = 1
        end = match.end()
        while end < len(text) and depth > 0:
            depth += {"{": 1, "}": -1}.get(text[end], 0)
            end += 1
        if entry_type not in NOT_ENTRIES:
            entries.append((entry_type, key, text[match.end() : end - 1]))
        position = end
    return entries


def normalise_doi(value: str | None) -> str | None:
    """A DOI in lowercase without its resolver prefix or trailing punctuation, or None if the value holds no DOI."""
    if not value:
        return None
    match = DOI.search(value.replace("\\_", "_"))
    return match.group(0).rstrip(".,;)").lower() if match else None


def normalise_title(text: str) -> str:
    """Lowercase ASCII words separated by single spaces, so that "Lassa fever: the road ahead." and "Lassa fever - the road ahead" compare equal."""
    ascii_text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    return " ".join(NOT_ALPHANUMERIC.sub(" ", ascii_text.lower()).split())


def latex_to_text(value: str) -> str:
    """Plain text from a LaTeX field value: {Lassa} becomes Lassa and {\\'e} becomes é."""
    try:
        return LATEX.latex_to_text(value)
    except Exception:  # noqa: BLE001 - pylatexenc raises several error types on malformed input; the raw value is still usable
        return value


def parse_year(fields: dict[str, str]) -> int | None:
    """The year field, or the year at the start of a Paperpile date field such as 2025-07-29."""
    for name in ("year", "date"):
        match = re.search(r"\b(1[89]\d\d|20\d\d)\b", fields.get(name, ""))
        if match:
            return int(match.group(1))
    return None


def parse_bib(text: str, cited: set[str] = frozenset()) -> list[BibEntry]:
    """Every entry of a .bib file, with its DOI and title normalised for matching, and whether its key is among the lowercase cited keys."""
    entries = []
    for _, key, body in split_entries(text):
        fields = parse_fields(body)
        # Some entries carry their DOI only in the url field, as a doi.org link.
        doi = normalise_doi(fields.get("doi")) or normalise_doi(
            fields.get("url") if "doi.org" in fields.get("url", "") else None
        )
        entries.append(
            BibEntry(
                key=key,
                doi=doi,
                title=normalise_title(latex_to_text(fields.get("title", ""))),
                year=parse_year(fields),
                cited=key.lower() in cited,
            )
        )
    return entries


def cited_keys(bbl_text: str) -> set[str]:
    """The keys the thesis cites, from the \\bibitem lines of its .bbl file, in lowercase: BibTeX keys are case-insensitive, and the .bbl may spell a key differently from the .bib."""
    return {key.lower() for key in BIBITEM.findall(bbl_text)}
